<?php

namespace AppBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotConfirmedCommand()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT C FROM AppBundle:Commande C WHERE C.status = 'false' "
            )
            ->getResult();
    }
    public function findConfirmedCommand()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT C FROM AppBundle:Commande C WHERE C.status = 'true' "
            )
            ->getResult();
    }    
}
