<?php

namespace AppBundle\Repository;

/**
 * LcommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LcommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByCommandeNumber($commNum)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT l FROM AppBundle:Lcommande l WHERE l.countNum = $commNum "
            )
            ->getResult();
    }
}
