<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
    * return Tache[]
    */
    public function findByUser(User $user): ? array
    {

        $qb =  $this->createQueryBuilder('p')
            ->andWhere('p.user = :user')
            ->setParameter('user', $user)
            ->getQuery();
            
            return $qb->execute();
        
    }
    public function findAllByPagination()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Product p ORDER BY p.libelle ASC'
            )
            ->getResult();
    }

    /**
    * return SubCategory[]
    */
    public function findAllBySubCategory($subC): ? array
    {
        $query = $this->createQueryBuilder('e')
        ->addSelect('r') // to make Doctrine actually use the join
        ->join('e.subCategory', 'r')
        ->where('r = :subc')
        ->setParameter('subc', $subC)
        ->getQuery();

    return $query->getResult();
    }

    public function findAvailaibleProduct()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT P FROM AppBundle:Product P WHERE P.status = 'available'"
            )
            ->getResult();
    }

    public function findNotAvailaibleProduct()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT P FROM AppBundle:Product P WHERE P.status = 'unavailable'"            )
            ->getResult();
    }         
}
