<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * return Tache[]
    */
    public function findByUser(User $user): ? array
    {

        $qb =  $this->createQueryBuilder('p')
            ->andWhere('p.user = :user')
            ->setParameter('user', $user)
            ->getQuery();
            
            return $qb->execute();
        
    }    
}
